### ISSUE TITLE
Problem Opening

### ISSUE THREAD

**Issue by zed7576** [C-Rodg/Coinbar#2]
This looks awesome, but I'm having a problem opening it. It won't load on my windows for some reason, and if I try to npm install and npm start the output is just "electron ." and nothing opens. Do you have any advice on how to open it?

**Comment by C-Rodg** [comment]
@quantyst Are you trying to do development on it or are you just trying to use it?  If you are just trying to use it go to [releases](https://github.com/C-Rodg/CryptoCap/releases) and download the proper version for your Windows machine and use that.  Let me know if you need some more guidance.

Thanks!

**Comment by C-Rodg** [comment]
Marking as closed. Please let me know if you have any further questions.
