### ISSUE TITLE
No shortcut + atypical installation config

### ISSUE THREAD

**Issue by Hub-O-Gits** [C-Rodg/Coinbar#5]
No shortcut is created upon installation. The user has to go searching for the executable, which can be found at "C:\Users\<username>\AppData\Local\cryptocap\CryptoCap.exe". The average user isn't going to know that.

Why doesn't it prompt for an installation location, or otherwise allow any user interaction.
Why does it install to AppData instead of Program Files?

**Comment by C-Rodg** [comment]
Hello! Thank you for your interest in CryptoCap.  Unfortunately, I no longer have the time to support this project, so it has been discontinued and removed from the app store.  I appreciate your interest though!
